#!/usr/bin/env python3
"""Embed the UI/ static files into firmware/src/web/web_assets.h.

Run from anywhere:
    python3 firmware/balancing_robot/tools/gen_web_assets.py

Re-run after editing index.html / css / js / vendor. The Arduino build picks
up the regenerated header on the next compile.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UI_DIR = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'UI'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'web', 'web_assets.h'))

MIME = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.ttf': 'font/ttf',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.json': 'application/json',
}

SKIP_DIRS = {'tests', '__pycache__', '.git'}


def collect():
    assets = []
    for root, dirs, files in os.walk(UI_DIR):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in sorted(files):
            ext = os.path.splitext(f)[1].lower()
            if ext not in MIME:
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, UI_DIR).replace(os.sep, '/')
            assets.append(('/' + rel, MIME[ext], full))
    assets.sort(key=lambda a: a[0])
    return assets


def as_c_bytes(data: bytes, name: str) -> str:
    # Text assets as raw string literal (delimiter collision-checked);
    # binary assets (ttf/png/...) as a hex byte array.
    delim = ')WEB_ASSET_END"'
    try:
        text = data.decode('utf-8')
        if delim not in text:
            return f'static const char {name}[] PROGMEM = R"WEB_ASSET_END({text})WEB_ASSET_END";'
    except UnicodeDecodeError:
        pass
    hexs = ''.join(f'0x{b:02x},' for b in data)
    return f'static const uint8_t {name}[] PROGMEM = {{{hexs}}};'


def main():
    assets = collect()
    if not any(a[0] == '/index.html' for a in assets):
        raise SystemExit('index.html not found under ' + UI_DIR)
    parts = [
        '// GENERATED by tools/gen_web_assets.py — do not edit by hand.',
        '// Re-run the script after changing UI/.',
        '#pragma once',
        '#include <Arduino.h>',
        '',
        'struct WebAsset { const char* path; const char* mime; const uint8_t* body; size_t len; };',
        '',
    ]
    entries = []
    for i, (route, mime, full) in enumerate(assets):
        data = open(full, 'rb').read()
        var = f'ASSET_{i}'
        decl = as_c_bytes(data, var)
        is_text = decl.lstrip().startswith('static const char')
        length_expr = f'sizeof({var}) - 1' if is_text else f'sizeof({var})'
        parts.append(decl)
        parts.append('')
        entries.append(f'  {{"{route}", "{mime}", (const uint8_t*){var}, {length_expr}}},')
    parts.append('static const WebAsset WEB_ASSETS[] PROGMEM = {')
    parts.extend(entries)
    parts.append('};')
    parts.append(f'static const size_t WEB_ASSET_COUNT = {len(entries)};')
    parts.append('')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(parts))
    total = sum(os.path.getsize(a[2]) for a in assets)
    print(f'wrote {OUT}: {len(assets)} assets, {total} bytes raw')


if __name__ == '__main__':
    main()
